### ISSUE TITLE
Merging scapy3k into scapy

### ISSUE THREAD

**Issue by SimplicityGuy** [phaethon/scapy#103]
It would be nice to have a single scapy package capable of being used on Python 2.7 and Python 3.x. Has there been any discussion to merge this project into the secdev/scapy project?

**Comment by phaethon** [comment]
scapy3k was started because secdev/scapy developers refused to add python3 support and suggested creating new independent branch, which is what I did. Parts of the code got rewritten and optimized utilizing the fact that python2 support is not an objective. Some functionality got created first in this project (e.g. PCAPNG support) and later secdev/scapy chose to clone the functionality with a different code. The major difference between the projects is string vs. bytes usage for packets, which makes writing python2/3 compatible code very inconvenient. So, I don't see any realistic merging scenario any time soon. First step would be for secdev/scapy to include at least a single reference to the existence of this project, which they chose not to do.

**Comment by SimplicityGuy** [comment]
Thank you for the in depth history and explanation. That's really unfortunate that the creators of scapy did not want py3k support and encouraged a fork.

Is there a good list of where the two have diverged, e.g. Features that exist in one but not the other, differences in functionality?

**Comment by phaethon** [comment]
I used to know the list ~year ago when I was actively porting, but I haven't followed secdev/scapy development lately. They have matched some of the differences (e.g. PCAPNG support) with their own implementations choosing not to use code from phaethon/scapy. There are still features that are unmatched, e.g. multiple traceroute (see http://wiki.networksecuritytoolkit.org/nstwiki/index.php/HowTo_Use_The_Scapy:_Multi-Traceroute_(MTR) ). If there would be somebody from the community willing to bring projects together - it would be great thing. Most of the changes in both projects are incremental and trivial to port across as the base itself shares a lot in common.

**Comment by phaethon** [comment]
As there is nothing practical that can be done in the scope of this project for the issue, I am closing the issue. Ready to open it when there are ideas how to get forward.
